### ISSUE TITLE
Problème de couleur sur la légende

### ISSUE THREAD

**Issue by meaz** [AtelierCartographie/Khartis#10]
Il y a un problème de couleur sur la légende: comme le montre l'image, il est censé y avoir 4 couleurs dans la légende, or, s'il y a bien 4 cases, les deux plus foncées sont en fait le même vert. Or, si on regarde la couleur de la France, on voit que l'un de ces deux verts devrait en fait montrer la couleur utilisée par la France.
![export_khartis](https://cloud.githubusercontent.com/assets/13604424/24577763/1cbba9dc-16d4-11e7-828b-b254285ebdcb.png)

**Comment by apezel** [comment]
@meaz Serait-il possible d'avoir le jeu de données qui pose problème. Ainsi qu'une capture d'écran du paneau de configuration de la visualisation ? Cela m'aiderait à résoudre le bug.
Merci.

**Comment by meaz** [comment]
Bonjour @apezel 

voici un zip avec le projet au format kh, les données au format csv ainsi qu'une capture d'écran. Je précise que peu importe la couleur choisie, j'ai toujours le même soucis.

[Données.zip](https://github.com/AtelierCartographie/Khartis/files/889949/Donnees.zip)

![screenshot](https://cloud.githubusercontent.com/assets/13604424/24608385/9c42cdf4-1876-11e7-9217-3d7333ecf6e0.png)

Merci

**Comment by apezel** [comment]
@maez @RouxRC Merci. J'ai corrigé le problème dans le dernier commit. Il faudra soit compiler l'application à partir des sources, soit attendre qu'une nouvelle version soit déployée en production.

**Comment by boogheta** [comment]
@TomBor La préprod s'est bien à jour automatiquement, voulez vous que je fasse une mise à jour de la prod ?
