### ISSUE TITLE
Gestion de la visualisation des données absentes

### ISSUE THREAD

**Issue by meaz** [AtelierCartographie/Khartis#15]
Ce serait pratique si on pouvait gérer la visualisation des données absentes. Comme on voit sur cette capture d'écran, je n'ai pas cette possibilité:
![02](https://user-images.githubusercontent.com/13604424/34482547-007177f2-efb9-11e7-9259-f21bb3653032.png)

En particulier, ce serait bien de pouvoir choisir des hachures pour ces données absentes lorsqu'on a choisit un dégradé du noir au blanc.

**Comment by TomBor** [comment]
Normalement ce cas de figure est géré que ce soit pas l'absence réelle de nombre ou l'indication d'un texte (ex : NA) ou les deux. Voir capture avec le fond monde et les données en exemple sur la sous-alimentation, l'absence à été passée en rose :   
![no-data](https://user-images.githubusercontent.com/8322713/34614844-1a6b97f6-f233-11e7-87b6-c11206403091.png)
![no-data-na](https://user-images.githubusercontent.com/8322713/34615220-6a552a56-f234-11e7-854a-12c0f2587139.png)


Par contre seulement deux actions sont possibles sur l'absence de données : afficher/masquer et changer de couleur. La possibilité de sélectionner des hachures est une très bonne idée que l'on devrait pouvoir implémenter en s'inspirant de ce qui est déjà disponible dans la visualisation "catégories > surfaces" :   
![hachure-picker](https://user-images.githubusercontent.com/8322713/34615078-d5ecaeb6-f233-11e7-95f7-85728e51bcb5.png)

**Comment by boogheta** [comment]
Petit doute néanmoins @TomBor : ne s'agit-il pas seulement des données pour lesquelles on n'a pas de valeur mais tout de même bien une ligne dans le fichier source ? Auquel cas la question porterait spécifiquement sur ce qui n'est pas dans la donnée (par exemple quand on ne part pas du modèle proposé pour le fond choisi)

**Comment by meaz** [comment]
Dans ce cas il y a un petit bogue: je suis sous debian stretch avec firefox 57: je ne vois pas la partie "Absence de données". Voici une capture d'écran pour le montrer:
![screenshot-2018-1-6 khartis](https://user-images.githubusercontent.com/13604424/34638245-eed9ec9c-f2c7-11e7-8e90-c155d818a921.png)

**Comment by boogheta** [comment]
Comme je le disais, je pense que c'est parce que tous les pays de votre fichier contiennent bien des données. Si vous le complétez avec une ligne par pays manquant (issu du modèle téléchargeable sur l'écran où l'on choisit son fond de carte) ceux ci apparaîtront.
Mais je pense effectivement que c'est quelque chose qui devrait être géré par ailleurs par l'appli

**Comment by meaz** [comment]
Non, je confirme que tous les pays n'ont pas des données. Ils sont d'ailleurs en noir sur cette carte:
![screenshot-2018-1-7 khartis](https://user-images.githubusercontent.com/13604424/34650734-35074d82-f3c6-11e7-9549-90e05a66e76a.png)

**Comment by TomBor** [comment]
Pouvez-vous partager votre jeu de données pour que l'on fasse des tests ?
Merci d'avance

**Comment by meaz** [comment]
Voilà.
[tourisme.zip](https://github.com/AtelierCartographie/Khartis/files/1612916/tourisme.zip)
Données téléchargées sur le site de la banque mondiale. J'ai juste modifié les titres des colonnes et supprimé qq colonnes.

**Comment by TomBor** [comment]
Merci !
Alors il y a bien un bug dans la reconnaissance des absences de données selon leurs écritures. Dans votre exemple, elles sont sous la forme de ".." (qui ne fonctionne pas), mais si on les remplace par du texte type "NA" ou même rien "" alors l'absence de données est bien reconnue. Nous allons essayer de corriger ça.  

Comme le disais @boogheta en dehors de ce bug le système d'absence de données regarde les blancs au sein des données importées par l'utilisateur mais pas avec le fonds de carte. Par exemple avec des données importées ne concernant que les pays africains et un fond de carte monde, le reste des pays dans les autres régions ne sera pas considéré comme "absence de données".   

La gestion des hachures des données absentes sera supportée dès la prochaine version de Khartis d'ici quelques semaines. Merci de nous l'avoir signalé/suggéré !

**Comment by meaz** [comment]
Merci à vous! Je viens de tester, effectivement en remplaçant les '..' par des vides, j'ai bien la possibilité de changer la couleur des données absentes.

**Comment by TomBor** [comment]
Bonjour,
La nouvelle [version 2.1.0](https://github.com/AtelierCartographie/Khartis/releases/tag/khartis-v2.1.0) est en ligne et corrige les deux points, à savoir : 
-   le support de l'absence de données avec des caractères de type ".." ou "-"
-   l'ajout des hachures dans la personnalisation des données absentes

Merci de vos remarques !
