### ISSUE TITLE
Fond de carte lors de l'export

### ISSUE THREAD

**Issue by meaz** [AtelierCartographie/Khartis#17]
Bonsoir,

il y a un petit problème lors de l'export de la carte que j'ai réalisée.
Quand j'utilise l'option "Fond de carte", voilà ce qui est colorisé:
![screenshot-2018-1-9 khartis](https://user-images.githubusercontent.com/13604424/34744817-c492c7f0-f58e-11e7-81b2-c62199a8a39c.png)
Voici les données utilisées: 
[tourisme.zip](https://github.com/AtelierCartographie/Khartis/files/1616808/tourisme.zip)

Alors que lorsque je teste avec les données d'exemple fournies par Khartis, ce sont tous les pays qui sont colorisés.

Deuxième chose: il faudrait plutôt appeler cette option "Couleur des pays" car "Fond de carte" fait plutôt penser aux mers et océans (d'ailleurs, ce serait bien de pouvoir les coloriser si besoin)

Merci

**Comment by TomBor** [comment]
Bonjour,

L'option "Fond de carte" colorie effectivement l'ensemble des pays/territoires et correspond à la vue de la carte sans visualisation.   
Et les visualisations viennent ensuite se superposer par dessus selon la logique des couches ou calques que l'on retrouve dans les logiciels d'images ou de dessin.    

Dans votre exemple, vos données ne couvrent pas la totalité des pays/territoires du fonds monde. Notamment l'Antarctique, le Sahara occidental et la Guyane ne sont pas dans votre tableau. Or la visualisation sous forme de surface de vos données vient se superposer et masquer la couleur des pays défini dans l'option "Fond de carte".   

Sur la non possibilité de changer la couleur de la mer, c'est un choix voulu. Khartis est dédié à la visualisation des données et ce type d'option peut être réalisé dans un logiciel de dessin en utilisant l'export svg. Mais si d'autres demandes identiques venaient nous pourrions revoir notre avis.

**Comment by meaz** [comment]
Merci c'est très clair. Je clos le soucis qui n'en est donc pas un!
