### ISSUE TITLE
Choix des dimensions export png

### ISSUE THREAD

**Issue by ltriay** [AtelierCartographie/Khartis#18]
Bonjour !

Merci pour ce super logiciel.

Le choix de la taille pour les exports .png ne semble pas être pris en compte. J'obtiens toujours une image d'environ 3.000 pixels de large. 

Pour info je re-exporte sans pb l'image svg avec Inkscape à la taille voulue.

**Comment by TomBor** [comment]
Bonjour,
Effectivement, le png exporté est plus grand que les dimensions affichées dans Khartis. Le but est de simuler une meilleure résolution (300dpi) pour assurer si besoin une impression de qualité.

Mais pour l'utilisateur cela peut être déroutant. Une amélioration de l'ergonomie ou de la fonctionnalité serait un plus.

**Comment by TomBor** [comment]
La prochaine version de Khartis aura une nouvelle gestion de l'export png qui sera plus intuitive pour l'utilisateur.
