### ISSUE TITLE
Rayures

### ISSUE THREAD

**Issue by ltriay** [AtelierCartographie/Khartis#21]
Une suggestion d'ajout de fonctionnalité : ajouter une visualisation avec des rayures dont la densitée varie au lieu d'augmenter la largeur des bandes (comme dans la visualisation actuelle).

**Comment by TomBor** [comment]
Bonjour,
En modifiant la largeur des hachures, on respecte la notion d'ordre que demande une carte choroplèthe. Les données sont ordonnées avec de petite et grande valeurs. La gamme de couleurs est elle aussi ordonnée, du clair au foncé.

Par contre en jouant sur la densité, c'est à dire la même hachure dont je fais varier l'échelle, on ne retrouve pas cette notion d'ordre.

Ci-dessous, un rapide exemple qui sera plus parlant. Il y a 4 classes de hachures représentées dans des carrés de 100x100px, une fois en variant la largeur et une autre fois en variant la densité. Pour chaque carré j'ai calculé le pourcentage de violet.

![test-hachure-largeur-vs-densite](https://user-images.githubusercontent.com/8322713/36027266-d7017142-0d9a-11e8-822c-a13df48a7f23.png)


Dans le premier cas, le pourcentage augmente ce qui équivaut bien au changement d'intensité de couleurs que l'on peut voir dans les rectangles.
Dans le second cas, les hachures sont bien différentes visuellement mais l'information donnée est la même.

**Comment by ltriay** [comment]
Ok merci pour l'explication !
