### ISSUE TITLE
Re-importer des données

### ISSUE THREAD

**Issue by ltriay** [AtelierCartographie/Khartis#22]
Bonjour,
Est-il possible de re-importer des données sans modifier le reste du projet (modification des valeurs) ?
Merci !

**Comment by TomBor** [comment]
Bonjour,
Non, ce n'est pas possible à ce jour de ré-importer des données tout en conservant les visualisations. Le coeur de Khartis est dans les représentations, la partie donnée se veut simple et ne permet pas de modifier à postériori des valeurs. Même si, ça pourrait être pratique à des moments.
