### ISSUE TITLE
Introducing new basemaps for thematic maps about germany

### ISSUE THREAD

**Issue by mukil** [AtelierCartographie/Khartis#5]
Hi all,
this issue is here to discuss and keep track of the progress on integrating two new german basemaps into the Khartis standard distribution.

The first basemap (on level NUTS-1) representing all 16 german states is now available in my [basemap-de-states](https://github.com/mukil/Khartis/tree/basemap-de-states) branch. After the changes described [in the following commit](https://github.com/mukil/Khartis/commit/fbf26cace5e3d4e65a38fa635b4bd0467124e6f0) I am able to select the new basemap and start designing it.

Now i have two questions:
1. Can i tweak or set the initial viewport for the map preview available in "Step 1"? When one selects "Allemagne > Land" the whole world is displayed. If so, how or is there something missing in my file?
2. I choose to make the basemaps available based on open data geometries published by the [Bundesamt für Kartographie und Geodäsie](http://www.geodatenzentrum.de/geodaten/gdz_rahmen.gdz_div?gdz_spr=eng&gdz_akt_zeile=5&gdz_anz_zeile=0&gdz_user_id=0). Officially, each map using these geometries should therefore include an attribution like described in the paragraph on [License & Usage rights](https://github.com/mukil/Khartis/tree/basemap-de-states/public/data/map/DE-2016#license-usage-rights).

Regarding the task at hand and preparing a new basemap, what i already found out is that:
- Each basemap is at best to be delivered as a topojson and it needs to have at least three layers/geometries (named, _poly_, _centroid_ and _border_). Furthermore it should contain identifiers/regional keys as properties on each of its features.
- For integrating a new basemap one needs to provide a dictionary which _maps_ corresponding identifiers/regional keys to e.g. label/place names or other standard identifier/keys users may want to use

I plan to continue to document adding a new basemap in the following [/public/data/map/DE-2016/README](https://github.com/mukil/Khartis/blob/basemap-de-states/public/data/map/DE-2016/README.md) and i am looking forward to get this done :)

Nice greetings!

**Comment by mukil** [comment]
Please note that to test-drive the new de-states basemap you manually need to add the following lines to your `/config/environment.js` (as that file is in our `.gitignore`):
```
      {
        id: "german states 2016",
        sources: [
          {
            source: "DE-2016/topojson/vg2500-BKG-NUTS1-combined.json",
          }
        ],
        dictionary: {
          source: "DE-BKG-NUTS1-2016.json",
          identifier: "RS"
        },
        examples: []
      },
```
And the following line to the "basemap" object in your respective (german, frencht, english) `app/locales/de|fr|en/translations.js` file:
```
    "german states 2016": "Germany > States (2016)",
```
To test-drive the new [de-districts](https://github.com/mukil/Khartis/tree/basemap-de-districts) basemap branch you manually need to add the following lines to your `/config/environment.js` and `app/locales/de|fr|en/translations.js`:

```
      {
        id: "german districts 2016",
        sources: [
          {
            source: "DE-2016/topojson/vg2500-BKG-NUTS3-combined.json",
          }
        ],
        dictionary: {
          source: "DE-STATIS-NUTS3-2016.json",
          identifier: "RS"
        },
        examples: [
          {
            id: "de_district_inhabitants",
            source: "de-destatis-Inhabitants-nuts3-2016.csv"
          }
        ]
      },
```

```
    "german districts 2016": "Germany > Districts (2016)",
```

**Comment by apezel** [comment]
Hi,

Thank for your help on Khartis ! Can you please make a pull request on master with your new basemap ?

Please add your map configuration into environment.js.tpl. As you said, environment.js isn't versioned.

You'll have to set the suitable projection for Germany too : 
```
source: "DE-2016/topojson/vg2500-BKG-NUTS3-combined.json",
projection "d3.geoMercator" //for example
```

I switched from D3.js v3 to D3.js v4 so projection name have changed (i.e. : d3.geo.mercator -> d3.geoMercator).

If you don't set the projection, Khartis will assume that it can be manually defined by the user (like the world map). It doesn't make sense for a country only map.

@TomBor may help you with this.

**Comment by TomBor** [comment]
Hi @mukil ,
To help you I write this page: [How to create a basemap for Khartis](https://github.com/AtelierCartographie/Khartis/wiki/How-to-create-a-basemap-for-Khartis). But you have already found most of it by yourself.

I have taken a look at your [basemap-de-states](https://github.com/mukil/Khartis/tree/basemap-de-states) branch. Everything look fine, except the `border` layer which need to be rename `line` (my mistake) but before I think it's better to redone it with the [`innerlines`](https://github.com/AtelierCartographie/Khartis/wiki/How-to-create-a-basemap-for-Khartis#line) command line of mapshaper.

For the config part, what is the official projection to be used with Germany ?

**Comment by mukil** [comment]
Hey @TomBor, thanks for the guide and your support!

I wil be able to redo the two basemaps according to the new guide at the end of next week (23/24.3) and then open up a pull request.

> For the config part, what is the official projection to be used with Germany ?

I asked a bit around and most of my colleagues prefer to use [Lambert conic](https://en.wikipedia.org/wiki/Lambert_conformal_conic_projection) or Gauss-Krüger ([transversale Mercator](https://en.wikipedia.org/wiki/Transverse_Mercator_projection)?) when creating thematic maps about germany.

As i envision it, the projection for rendering country-level maps (as the german basemap i am workin on) should remain interchangeable in Khartis. From my perspective the easyness of projecting the very same geodata through different perspectives is a clear strengths of Khartis. Is there something I can to do so this remains or becomes possible?

**Comment by TomBor** [comment]
Thanks @mukil 
We already use a Lambert conic for France, and we know that it work well with Khartis. So I suggest to use it again for Germany. But as you can see below, I need two parameters: latitude where the cone is secant (`parallels`) and position of origin point (`rotate`).

`projection: "d3.geoConicConformal()", transforms:{rotate: [-3, -46.3], parallels: [44, 49]}`

About your last remarks, on the contrary of world basemap, with national basemaps we don't offer the multiple projection functionality. And we don't consider to add it, not because it's not possible, but rather because it doesn't change radically the shape of the country. Differences between officials projections at a national level are important for surveyors or experts who need cartography of precision, but for a thematic map with a simplify basemap it is not sufficiently perceptible.

**Comment by mukil** [comment]
Ok, great. For your release I will try to set the lambert conic projection as the default projection for german basemaps in Khartis. Thanks also for sharing your perspective on my remarks :)

> I wil be able to redo the two basemaps according to the new guide at the end of next week (23/24.3) ..

And sorry, the correct delivery date for the changes ("the end of next week") is of course the 16/17.3.

Cheers!

**Comment by mukil** [comment]
Hey @TomBor!

Today i was finally able to revise and succesfully integrate the two german basemaps according to your guide. The results are now available with the [basemaps-de-mukil](https://github.com/mukil/Khartis/tree/basemaps-de-mukil) branch. Everything seems to be fine now with my basemaps and that version of Khartis.

However, after merging these with the latest changes in the 'master' branch i discoverred a new error. Most probably it is related to the major upgrade of the three d3.js depdendencies. I was yet unable to better understand the issue but it only seems to be thrown with my german basemaps. I would be very happy if someone could have a look and try to identify the issue. It seems to occur only when starting to add more (visualization) layers (step 2) to the two german basemaps i made. The following error is thrown and as a result no further layer can be added to the map;

`d3.js:6353 Uncaught Error: invalid format: 0,.2.9999999999999996f`

Here is the full stacktrace from Chromium Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04 (64-bit).

```
Error: invalid format: 0,.2.9999999999999996f  vendor.js:86087:44
	FormatSpecifier http://localhost:4200/assets/vendor.js:86087:44
	formatSpecifier http://localhost:4200/assets/vendor.js:86081:10
	newFormat http://localhost:4200/assets/vendor.js:86145:17
	bindLayer/< http://localhost:4200/assets/khartis.js:8501:27
	["/home/malted/source/ifl/Khartis/node_modules/d3/build/d3.js"]</</selection_each http://localhost:4200/assets/vendor.js:80967:28
	bindLayer http://localhost:4200/assets/khartis.js:8496:9
	["/home/malted/source/ifl/Khartis/node_modules/d3/build/d3.js"]</</selection_call http://localhost:4200/assets/vendor.js:80931:3
	update http://localhost:4200/assets/khartis.js:8594:18
	_npmD3.default.selection.prototype.enterUpdate http://localhost:4200/assets/khartis.js:33729:7
	exports.default<.drawLegend< http://localhost:4200/assets/khartis.js:8587:7
	applyStr http://localhost:4200/assets/vendor.js:36705:16
	sendEvent http://localhost:4200/assets/vendor.js:30495:11
	notifyObservers http://localhost:4200/assets/vendor.js:34061:7
	propertyDidChange http://localhost:4200/assets/vendor.js:33888:5
	ChainWatchers.prototype.notify http://localhost:4200/assets/vendor.js:28153:9
	chainsDidChange http://localhost:4200/assets/vendor.js:33977:7
	propertyDidChange http://localhost:4200/assets/vendor.js:33887:5
	EachProxy.prototype.contentKeyDidChange http://localhost:4200/assets/vendor.js:50784:7
	applyStr http://localhost:4200/assets/vendor.js:36705:16
	sendEvent http://localhost:4200/assets/vendor.js:30495:11
	notifyObservers http://localhost:4200/assets/vendor.js:34061:7
	propertyDidChange http://localhost:4200/assets/vendor.js:33888:5
	set http://localhost:4200/assets/vendor.js:34326:11
	exports.default<.set http://localhost:4200/assets/vendor.js:48598:14
	notifyDefferedChange http://localhost:4200/assets/khartis.js:4969:13
	GraphLayer<.deferredChange< http://localhost:4200/assets/khartis.js:2901:7
	Backburner.prototype.run http://localhost:4200/assets/vendor.js:14616:18
	Backburner.prototype.debounce/timer< http://localhost:4200/assets/vendor.js:14920:11
```
And on another occasion:
```
Uncaught Error: invalid format: 0,.2.9999999999999996f@d3.js:6353
FormatSpecifier @ d3.js:6353formatSpecifier @ d3.js:6347newFormat @ d3.js:6411(anonymous function) @ legend.js:160selection_each @ d3.js:1233bindLayer @ legend.js:155selection_call @ d3.js:1197update @ legend.js:253_npmD3.default.selection.enterUpdate @ d3proto.js:17(anonymous function) @ legend.js:248applyStr @ ember.debug.js:22777sendEvent @ ember.debug.js:16567notifyObservers @ ember.debug.js:20133propertyDidChange @ ember.debug.js:19960notify @ ember.debug.js:14225chainsDidChange @ ember.debug.js:20049propertyDidChange @ ember.debug.js:19959enumerableContentDidChange @ ember.debug.js:33753arrayContentDidChange @ ember.debug.js:32449replace @ ember.debug.js:37252insertAt @ ember.debug.js:34138unshiftObject @ ember.debug.js:34273addLayer @ controller.js:295send @ ember.debug.js:31965runRegisteredAction @ ember.debug.js:29021run @ ember.debug.js:688run @ ember.debug.js:20589handler @ ember.debug.js:29015(anonymous function) @ ember.debug.js:43675dispatch @ jquery.js:4435elemData.handle @ jquery.js:4121
ember.debug.js:52502 Attempting transition to graph.layer
```
After this error appears, adding another layer does not work anymore. New layers elements are after one reloads the page. But after reloading the page the component normally rendering the map (visualization live preview) can not be bootstrapped anymore (=does not appear).

Pulling in the latest changes from master required me to update the following modules:
```
Missing npm packages: 
Package: @types/d3
  * Specified: ^4.5.0
  * Installed: (not installed)

Package: d3
  * Specified: ^4.7.1
  * Installed: 3.5.17

Package: d3-geo-projection
  * Specified: ^1.2.2
  * Installed: 0.2.16
```
To double check that this issue is unrelated to the new basemaps i produced I additionally introduced these into the branch with the previous version of Khartis i was working on (from 16 days ago, which is [629c4728233388b0826e83ab0a75b16c33b176cd](https://github.com/mukil/Khartis/commit/629c4728233388b0826e83ab0a75b16c33b176cd)). There everything seems to work fine. At least no such error is thrown. I hope we can track down this issue somehow. My current observation tells me that it has to do with the basemaps files but of course I could be wrong. Does this error look somehow familiar to someone or do you have any ideas how i could fureher track this down?

Thanks for your help & Kind regards.

**Comment by apezel** [comment]
@mukil Hi, Thanks for your work on Khartis. Can you please try to rebase with the latest version commit ? The problem you're having may not be related to the basemap. I made a change that should resolve it.

**Comment by mukil** [comment]
Hey @apezel, great! Thank for your quick reply! With your latest change the two new basemap work don't throw that error anymore. But I accidentialy screwed up the `rebase` by doing a `git pull upstream`, which automaticallly triggered a `merge`.... I just started to read/learn about what [git rebase](https://github.com/AtelierCartographie/Khartis) is and will see/try if i can correct that mistake.

Thanks!

**Comment by apezel** [comment]
Hi @mukil. Thank you for your great work on khartis. Rebase isn't required if you're not confortable with it. You can simply pull the latest release and merge it before your pull request. We added two new tooltips that need translation but that's not urgent so if you don't have time to update your code, can you please do your pull request "as is".
Bye.

**Comment by mukil** [comment]
Hey @apezel, ok! I translated the new tooltips and created pull request #9.
Thanks for your kind support!

**Comment by TomBor** [comment]
@mukil the two basemaps and the german version is online at the official adress!
http://www.sciencespo.fr/cartographie/khartis/en/
Thanks for your contribution.
