### ISSUE TITLE
Make 2 more tooltips and 1 label translatable & add english and german translation

### ISSUE THREAD

**Issue by mukil** [AtelierCartographie/Khartis#7]
I identified three texts in the UI which are not yet translatable. Would be great if we can include them in the translation files.

- Label (Step 2/Anomalies detected): "En savoir plus"
- Tooltip (Step 1/Correcting Geographic References): "Corrige"
- Tooltip (Step 1/Données, on Layers): "Aucune erreur détectée"

I could upload some screenshots if it helps.

**Comment by apezel** [comment]
Thanks. I added 3 properties : 
```
project.step2.import.correct
project.step2.import.noError
visualization.warning.rule.count.about
```

**Comment by mukil** [comment]
Merci!
