### ISSUE TITLE
"undefined" values in Name column of table assembled by "Télécharger le modèle (.csv)"

### ISSUE THREAD

**Issue by mukil** [AtelierCartographie/Khartis#8]
Hello!

I am not yet sure why this is the case but i noticed the following issue:
When I click "Télécharger le modèle (.csv)" (Step 1) at the two new german basemaps (see [this branch](https://github.com/mukil/Khartis/tree/basemaps-de-mukil)) all values in the "NAME" column seem to be "undefined".

- Is (or should) the geographical place name(s) be specified in the dictionary of a basemap?
- Is there a convention for a specific key/id (property name) which carries the name offered in the downloaded model?

Thanks for your support!

**Comment by TomBor** [comment]
We don't use convention in dictionary except for the first column always named "ID".

But I think @apezel will be able to indicate you if it's the reason.

**Comment by TomBor** [comment]
I just change in lower case the "NAME" column. But I can't explain the nature of the problem.
